import { Language } from '@/context/LanguageContext'

export interface EUCompliance {
  gdprCompliant: boolean | 'partial'
  euAiActReady: boolean
  dataLocation: string
  hasEuDataResidency: boolean | 'partial'
  dpaAvailable: boolean
  certifications: string[]
  complianceNote: Record<Language, string>
}

export interface Agent {
  slug: string
  name: string
  description: Record<Language, string>
  longDescription: Record<Language, string>
  category: string
  url: string
  tags: string[]
  free: boolean
  pricing: Record<Language, string>
  vendor: string
  founded: string
  headquarters: string
  euCompliance: EUCompliance
}

export const CATEGORIES: { id: string; labelKey: string; icon: string }[] = [
  { id: 'all', labelKey: 'directory.cat.all', icon: 'Grid' },
  { id: 'assistant', labelKey: 'directory.cat.assistant', icon: 'Chat' },
  { id: 'content', labelKey: 'directory.cat.content', icon: 'Pen' },
  { id: 'productivity', labelKey: 'directory.cat.productivity', icon: 'Zap' },
  { id: 'analytics', labelKey: 'directory.cat.analytics', icon: 'Chart' },
  { id: 'creative', labelKey: 'directory.cat.creative', icon: 'Palette' },
  { id: 'dev', labelKey: 'directory.cat.dev', icon: 'Code' },
]

export const AGENTS: Agent[] = [
  {
    slug: 'chatgpt',
    name: 'ChatGPT',
    description: {
      fr: 'Assistant IA polyvalent par OpenAI. Conversation, rédaction, analyse et programmation.',
      en: 'Versatile AI assistant by OpenAI. Conversation, writing, analysis and coding.',
      lb: 'Villsäitegen KI-Assistent vun OpenAI. Konversatioun, Schreiwen, Analyse a Programméierung.',
      de: 'Vielseitiger KI-Assistent von OpenAI. Konversation, Schreiben, Analyse und Programmierung.',
      it: 'Assistente IA versatile di OpenAI. Conversazione, scrittura, analisi e programmazione.',
      pt: 'Assistente IA versátil da OpenAI. Conversação, escrita, análise e programação.',
    },
    longDescription: {
      fr: "ChatGPT est l'assistant IA le plus populaire au monde, développé par OpenAI. Il excelle dans la conversation naturelle, la rédaction de contenu, l'analyse de données, la programmation et le raisonnement complexe. Les plans Business et Enterprise offrent une conformité RGPD complète avec résidence de données dans l'UE.",
      en: 'ChatGPT is the most popular AI assistant in the world, developed by OpenAI. It excels at natural conversation, content writing, data analysis, coding and complex reasoning. Business and Enterprise plans offer full GDPR compliance with EU data residency.',
      lb: 'ChatGPT ass de beléifsten KI-Assistent op der Welt, entwéckelt vun OpenAI. Et excelléiert an natierlecher Konversatioun, Inhaltsschreiwen, Datenanalyse, Programméierung a komplexem Résonement.',
      de: 'ChatGPT ist der beliebteste KI-Assistent der Welt, entwickelt von OpenAI. Er zeichnet sich durch natürliche Konversation, Inhaltserstellung, Datenanalyse, Programmierung und komplexes Denken aus.',
      it: "ChatGPT è l'assistente IA più popolare al mondo, sviluppato da OpenAI. Eccelle nella conversazione naturale, scrittura di contenuti, analisi dati, programmazione e ragionamento complesso.",
      pt: 'ChatGPT é o assistente IA mais popular do mundo, desenvolvido pela OpenAI. Destaca-se na conversação natural, escrita de conteúdos, análise de dados, programação e raciocínio complexo.',
    },
    category: 'assistant',
    url: 'https://chat.openai.com',
    tags: ['GPT-4', 'Multimodal'],
    free: true,
    pricing: {
      fr: 'Gratuit (limité) · Plus : 20 $/mois · Team : 25 $/mois · Enterprise : sur devis',
      en: 'Free (limited) · Plus: $20/mo · Team: $25/mo · Enterprise: custom pricing',
      lb: 'Gratis (limitéiert) · Plus: 20 $/Mount · Team: 25 $/Mount · Enterprise: op Ufro',
      de: 'Kostenlos (begrenzt) · Plus: 20 $/Monat · Team: 25 $/Monat · Enterprise: auf Anfrage',
      it: 'Gratuito (limitato) · Plus: 20 $/mese · Team: 25 $/mese · Enterprise: su richiesta',
      pt: 'Gratuito (limitado) · Plus: 20 $/mês · Team: 25 $/mês · Enterprise: sob consulta',
    },
    vendor: 'OpenAI',
    founded: '2022',
    headquarters: 'San Francisco, USA',
    euCompliance: {
      gdprCompliant: true,
      euAiActReady: true,
      dataLocation: 'US (default); EU available for Enterprise/API',
      hasEuDataResidency: true,
      dpaAvailable: true,
      certifications: ['SOC 2 Type II', 'ISO 27001', 'ISO 27017', 'ISO 27018', 'ISO 27701', 'CSA STAR'],
      complianceNote: {
        fr: "Conformité RGPD complète pour les plans Business/Enterprise/API. Le plan gratuit ne dispose pas de DPA. OpenAI Ireland Ltd est l'entité contractante pour les clients de l'EEE. Signataire du Code de pratique de l'UE pour l'IA.",
        en: 'Full GDPR compliance for Business/Enterprise/API plans. Free plan does not have a DPA. OpenAI Ireland Ltd is the contracting entity for EEA customers. Signatory of the EU Code of Practice for AI.',
        lb: "Voll RGPD-Konformitéit fir Business/Enterprise/API-Plangen. De gratis Plang huet keen DPA. OpenAI Ireland Ltd ass d'Vertragspartei fir EWR-Clienten.",
        de: 'Volle DSGVO-Konformität für Business/Enterprise/API-Pläne. Der kostenlose Plan hat keine AVV. OpenAI Ireland Ltd ist der Vertragspartner für EWR-Kunden.',
        it: "Piena conformità GDPR per i piani Business/Enterprise/API. Il piano gratuito non ha un DPA. OpenAI Ireland Ltd è l'entità contrattuale per i clienti SEE.",
        pt: 'Conformidade RGPD completa para planos Business/Enterprise/API. O plano gratuito não tem DPA. OpenAI Ireland Ltd é a entidade contratante para clientes do EEE.',
      },
    },
  },
  {
    slug: 'claude',
    name: 'Claude',
    description: {
      fr: "Assistant IA par Anthropic. Excellente compréhension, rédaction longue et analyse de documents.",
      en: 'AI assistant by Anthropic. Excellent comprehension, long-form writing and document analysis.',
      lb: 'KI-Assistent vun Anthropic. Exzellent Verständnis, laangt Schreiwen an Dokumentanalyse.',
      de: 'KI-Assistent von Anthropic. Hervorragendes Verständnis, Langtext und Dokumentenanalyse.',
      it: "Assistente IA di Anthropic. Eccellente comprensione, scrittura lunga e analisi di documenti.",
      pt: 'Assistente IA da Anthropic. Excelente compreensão, escrita longa e análise de documentos.',
    },
    longDescription: {
      fr: "Claude est un assistant IA développé par Anthropic, reconnu pour sa compréhension nuancée, sa rédaction longue de haute qualité et son analyse approfondie de documents. Premier fournisseur de LLM à obtenir la certification ISO 42001 (systèmes de management de l'IA). Résidence de données UE disponible pour les clients Enterprise.",
      en: 'Claude is an AI assistant developed by Anthropic, known for nuanced understanding, high-quality long-form writing and in-depth document analysis. First LLM provider to achieve ISO 42001 (AI management systems) certification. EU data residency available for Enterprise customers.',
      lb: 'Claude ass e KI-Assistent entwéckelt vun Anthropic, bekannt fir nuancéiert Verständnis, héichqualitativ laangt Schreiwen an déif Dokumentanalyse.',
      de: 'Claude ist ein KI-Assistent von Anthropic, bekannt für nuanciertes Verständnis, hochwertige Langtexte und tiefgehende Dokumentenanalyse.',
      it: "Claude è un assistente IA sviluppato da Anthropic, noto per la comprensione sfumata, la scrittura lunga di alta qualità e l'analisi approfondita dei documenti.",
      pt: 'Claude é um assistente IA desenvolvido pela Anthropic, conhecido pela compreensão matizada, escrita longa de alta qualidade e análise aprofundada de documentos.',
    },
    category: 'assistant',
    url: 'https://claude.ai',
    tags: ['Anthropic', 'Documents'],
    free: true,
    pricing: {
      fr: 'Gratuit (limité) · Pro : 20 $/mois · Team : 25 $/mois · Enterprise : sur devis',
      en: 'Free (limited) · Pro: $20/mo · Team: $25/mo · Enterprise: custom pricing',
      lb: 'Gratis (limitéiert) · Pro: 20 $/Mount · Team: 25 $/Mount · Enterprise: op Ufro',
      de: 'Kostenlos (begrenzt) · Pro: 20 $/Monat · Team: 25 $/Monat · Enterprise: auf Anfrage',
      it: 'Gratuito (limitato) · Pro: 20 $/mese · Team: 25 $/mese · Enterprise: su richiesta',
      pt: 'Gratuito (limitado) · Pro: 20 $/mês · Team: 25 $/mês · Enterprise: sob consulta',
    },
    vendor: 'Anthropic',
    founded: '2023',
    headquarters: 'San Francisco, USA',
    euCompliance: {
      gdprCompliant: true,
      euAiActReady: true,
      dataLocation: 'US (default); EU via AWS Frankfurt/Paris for Enterprise',
      hasEuDataResidency: true,
      dpaAvailable: true,
      certifications: ['SOC 2 Type II', 'ISO 27001:2022', 'ISO/IEC 42001:2023'],
      complianceNote: {
        fr: "Premier fournisseur de LLM certifié ISO 42001 (gestion IA). DPA auto-intégré aux conditions commerciales. Résidence de données UE pour les clients Enterprise via AWS Francfort/Paris. Signataire du Code de pratique de l'UE pour l'IA.",
        en: 'First LLM provider certified ISO 42001 (AI management). DPA auto-incorporated into commercial terms. EU data residency for Enterprise via AWS Frankfurt/Paris. Signatory of the EU Code of Practice for AI.',
        lb: "Éischte LLM-Ubidder mat ISO 42001-Zertifizéierung. DPA automatesch an d'kommerziell Konditiounen integréiert. EU-Datenresidenz fir Enterprise iwwer AWS.",
        de: 'Erster LLM-Anbieter mit ISO 42001-Zertifizierung. AVV automatisch in Geschäftsbedingungen integriert. EU-Datenresidenz für Enterprise über AWS Frankfurt/Paris.',
        it: "Primo fornitore LLM certificato ISO 42001 (gestione IA). DPA auto-incorporato nei termini commerciali. Residenza dati UE per Enterprise via AWS Francoforte/Parigi.",
        pt: 'Primeiro fornecedor de LLM certificado ISO 42001 (gestão IA). DPA auto-incorporado nos termos comerciais. Residência de dados UE para Enterprise via AWS Frankfurt/Paris.',
      },
    },
  },
  {
    slug: 'perplexity',
    name: 'Perplexity',
    description: {
      fr: "Moteur de recherche IA avec sources citées. Idéal pour la veille et la recherche d'informations.",
      en: 'AI search engine with cited sources. Perfect for research and information gathering.',
      lb: 'KI-Sichmaschinn mat zitéierte Quellen. Ideal fir Recherche an Informatiounssammlung.',
      de: 'KI-Suchmaschine mit zitierten Quellen. Ideal für Recherche und Informationssammlung.',
      it: 'Motore di ricerca IA con fonti citate. Perfetto per ricerche e raccolta informazioni.',
      pt: 'Motor de busca IA com fontes citadas. Perfeito para pesquisa e recolha de informação.',
    },
    longDescription: {
      fr: "Perplexity est un moteur de recherche alimenté par l'IA qui fournit des réponses avec des sources citées. Idéal pour la veille concurrentielle, la recherche de marché et la vérification des faits. DPA disponible uniquement pour les plans Enterprise Pro et API.",
      en: 'Perplexity is an AI-powered search engine that provides answers with cited sources. Ideal for competitive intelligence, market research and fact-checking. DPA available only for Enterprise Pro and API plans.',
      lb: 'Perplexity ass eng KI-bedriwwen Sichmaschinn déi Äntwerten mat zitéierte Quellen liwwert. Ideal fir Konkurrenziwwerwaachung, Maartrecherche a Faktenverifikatioun.',
      de: 'Perplexity ist eine KI-gestützte Suchmaschine mit zitierten Quellen. Ideal für Wettbewerbsanalyse, Marktforschung und Faktenprüfung.',
      it: "Perplexity è un motore di ricerca IA che fornisce risposte con fonti citate. Ideale per intelligence competitiva, ricerche di mercato e verifica dei fatti.",
      pt: 'Perplexity é um motor de busca IA que fornece respostas com fontes citadas. Ideal para inteligência competitiva, pesquisa de mercado e verificação de factos.',
    },
    category: 'assistant',
    url: 'https://perplexity.ai',
    tags: ['Search', 'Sources'],
    free: true,
    pricing: {
      fr: 'Gratuit (limité) · Pro : 20 $/mois · Enterprise Pro : sur devis',
      en: 'Free (limited) · Pro: $20/mo · Enterprise Pro: custom pricing',
      lb: 'Gratis (limitéiert) · Pro: 20 $/Mount · Enterprise Pro: op Ufro',
      de: 'Kostenlos (begrenzt) · Pro: 20 $/Monat · Enterprise Pro: auf Anfrage',
      it: 'Gratuito (limitato) · Pro: 20 $/mese · Enterprise Pro: su richiesta',
      pt: 'Gratuito (limitado) · Pro: 20 $/mês · Enterprise Pro: sob consulta',
    },
    vendor: 'Perplexity AI',
    founded: '2022',
    headquarters: 'San Francisco, USA',
    euCompliance: {
      gdprCompliant: 'partial',
      euAiActReady: false,
      dataLocation: 'US (AWS)',
      hasEuDataResidency: false,
      dpaAvailable: true,
      certifications: ['SOC 2 Type II', 'PCI DSS'],
      complianceNote: {
        fr: "Conformité RGPD auto-déclarée mais non vérifiée par les autorités UE. DPA disponible pour Enterprise Pro et API uniquement. Pas de résidence de données UE. Les plans Free/Pro utilisent les données pour l'entraînement.",
        en: 'Self-declared GDPR compliance, not independently verified by EU authorities. DPA available for Enterprise Pro and API only. No EU data residency. Free/Pro plans use data for training.',
        lb: 'Selwer deklaréiert RGPD-Konformitéit, net onofhängeg vun EU-Autoritéiten verifizéiert. DPA nëmme fir Enterprise Pro an API.',
        de: 'Selbsterklärte DSGVO-Konformität, nicht unabhängig von EU-Behörden verifiziert. AVV nur für Enterprise Pro und API verfügbar.',
        it: "Conformità GDPR auto-dichiarata, non verificata dalle autorità UE. DPA disponibile solo per Enterprise Pro e API.",
        pt: 'Conformidade RGPD auto-declarada, não verificada pelas autoridades da UE. DPA disponível apenas para Enterprise Pro e API.',
      },
    },
  },
  {
    slug: 'jasper',
    name: 'Jasper',
    description: {
      fr: 'Plateforme de contenu marketing IA. Génère des articles, publicités et contenus de marque.',
      en: 'AI marketing content platform. Generates articles, ads and brand content.',
      lb: 'KI-Marketing-Inhalt Plattform. Generéiert Artikelen, Reklammen a Markeninhalt.',
      de: 'KI-Marketing-Content-Plattform. Erstellt Artikel, Werbung und Markeninhalte.',
      it: 'Piattaforma di contenuti marketing IA. Genera articoli, pubblicità e contenuti di marca.',
      pt: 'Plataforma de conteúdo marketing IA. Gera artigos, anúncios e conteúdo de marca.',
    },
    longDescription: {
      fr: "Jasper est une plateforme de contenu marketing alimentée par l'IA. Elle génère des articles de blog, des publicités, des emails marketing et du contenu de marque optimisé pour le SEO. Les utilisateurs conservent 100 % de la propriété du contenu généré.",
      en: 'Jasper is an AI-powered marketing content platform. It generates blog posts, ads, marketing emails and SEO-optimized brand content. Users retain 100% ownership of generated content.',
      lb: 'Jasper ass eng KI-bedriwwen Marketing-Inhalt-Plattform. Et generéiert Blogartikel, Reklammen, Marketing-Emailen a SEO-optimiséierte Markeninhalt.',
      de: 'Jasper ist eine KI-gestützte Marketing-Content-Plattform. Sie erstellt Blogartikel, Werbeanzeigen, Marketing-E-Mails und SEO-optimierte Markeninhalte.',
      it: "Jasper è una piattaforma di contenuti marketing alimentata dall'IA. Genera articoli, pubblicità, email marketing e contenuti di marca ottimizzati per il SEO.",
      pt: 'Jasper é uma plataforma de conteúdo marketing alimentada por IA. Gera artigos, anúncios, emails marketing e conteúdo de marca otimizado para SEO.',
    },
    category: 'content',
    url: 'https://jasper.ai',
    tags: ['Marketing', 'SEO'],
    free: false,
    pricing: {
      fr: 'Creator : 49 $/mois · Pro : 69 $/mois · Business : sur devis',
      en: 'Creator: $49/mo · Pro: $69/mo · Business: custom pricing',
      lb: 'Creator: 49 $/Mount · Pro: 69 $/Mount · Business: op Ufro',
      de: 'Creator: 49 $/Monat · Pro: 69 $/Monat · Business: auf Anfrage',
      it: 'Creator: 49 $/mese · Pro: 69 $/mese · Business: su richiesta',
      pt: 'Creator: 49 $/mês · Pro: 69 $/mês · Business: sob consulta',
    },
    vendor: 'Jasper AI',
    founded: '2021',
    headquarters: 'Austin, USA',
    euCompliance: {
      gdprCompliant: true,
      euAiActReady: false,
      dataLocation: 'US',
      hasEuDataResidency: false,
      dpaAvailable: true,
      certifications: ['SOC 2 Type II'],
      complianceNote: {
        fr: "Conforme RGPD avec DPA incluant des CCT. Propriété complète du contenu pour l'utilisateur. Données non utilisées pour l'entraînement sauf opt-in. Chiffrement AES-256 au repos.",
        en: 'GDPR compliant with DPA including SCCs. Full content ownership for users. No model training on user data unless opted in. AES-256 encryption at rest.',
        lb: 'RGPD-konform mat DPA inklusive CCT. Voll Inhaltsbesëtzrecht fir de Benotzer. Keng Modellentraîning op Benotzerdaten ouni Opt-in.',
        de: 'DSGVO-konform mit AVV einschließlich SCC. Vollständige Inhaltseigentümerschaft für Benutzer. Kein Modelltraining mit Benutzerdaten ohne Opt-in.',
        it: "Conforme GDPR con DPA che include SCC. Proprietà completa dei contenuti per l'utente. Nessun training su dati utente senza opt-in.",
        pt: 'Conforme RGPD com DPA incluindo CCT. Propriedade completa do conteúdo para o utilizador. Sem treino em dados do utilizador sem opt-in.',
      },
    },
  },
  {
    slug: 'copy-ai',
    name: 'Copy.ai',
    description: {
      fr: "Rédacteur IA pour le copywriting. Emails, posts réseaux sociaux, descriptions produits.",
      en: 'AI copywriter. Emails, social media posts, product descriptions.',
      lb: 'KI-Copywriter. Emailen, Social Media Posts, Produktbeschreiwungen.',
      de: 'KI-Copywriter. E-Mails, Social-Media-Posts, Produktbeschreibungen.',
      it: 'Copywriter IA. Email, post social media, descrizioni prodotti.',
      pt: 'Copywriter IA. Emails, posts redes sociais, descrições de produtos.',
    },
    longDescription: {
      fr: "Copy.ai est un rédacteur IA spécialisé en copywriting. Il génère des emails, des posts réseaux sociaux, des descriptions produits et du contenu publicitaire. Pas de partage de données entre clients.",
      en: 'Copy.ai is an AI copywriter specialized in marketing copy. It generates emails, social media posts, product descriptions and ad copy. No cross-customer data sharing.',
      lb: 'Copy.ai ass e KI-Copywriter spezialiséiert op Marketing-Texter. Et generéiert Emailen, Social Media Posts, Produktbeschreiwungen an Reklammentexter.',
      de: 'Copy.ai ist ein KI-Copywriter, spezialisiert auf Marketingtexte. Generiert E-Mails, Social-Media-Posts, Produktbeschreibungen und Werbetexte.',
      it: 'Copy.ai è un copywriter IA specializzato in testi marketing. Genera email, post social, descrizioni prodotti e testi pubblicitari.',
      pt: 'Copy.ai é um copywriter IA especializado em textos marketing. Gera emails, posts sociais, descrições de produtos e textos publicitários.',
    },
    category: 'content',
    url: 'https://copy.ai',
    tags: ['Copywriting', 'Social'],
    free: true,
    pricing: {
      fr: 'Gratuit (2 000 mots/mois) · Pro : 49 $/mois · Enterprise : sur devis',
      en: 'Free (2,000 words/mo) · Pro: $49/mo · Enterprise: custom pricing',
      lb: 'Gratis (2.000 Wierder/Mount) · Pro: 49 $/Mount · Enterprise: op Ufro',
      de: 'Kostenlos (2.000 Wörter/Monat) · Pro: 49 $/Monat · Enterprise: auf Anfrage',
      it: 'Gratuito (2.000 parole/mese) · Pro: 49 $/mese · Enterprise: su richiesta',
      pt: 'Gratuito (2.000 palavras/mês) · Pro: 49 $/mês · Enterprise: sob consulta',
    },
    vendor: 'Copy.ai',
    founded: '2020',
    headquarters: 'Memphis, USA',
    euCompliance: {
      gdprCompliant: 'partial',
      euAiActReady: false,
      dataLocation: 'US',
      hasEuDataResidency: false,
      dpaAvailable: false,
      certifications: ['SOC 2 Type II'],
      complianceNote: {
        fr: "Conformité RGPD déclarée avec représentant UE désigné. Pas de DPA publiquement disponible. Pas de résidence de données UE. Utilise OpenAI comme sous-traitant.",
        en: 'Declared GDPR compliance with appointed EU representative. No publicly available DPA. No EU data residency. Uses OpenAI as subprocessor.',
        lb: 'Deklaréiert RGPD-Konformitéit mat ernanntem EU-Vertrieder. Keen ëffentlech verfügbaren DPA. Keng EU-Datenresidenz.',
        de: 'Erklärte DSGVO-Konformität mit ernanntem EU-Vertreter. Keine öffentlich verfügbare AVV. Keine EU-Datenresidenz.',
        it: "Conformità GDPR dichiarata con rappresentante UE designato. Nessun DPA pubblicamente disponibile.",
        pt: 'Conformidade RGPD declarada com representante UE designado. Nenhum DPA publicamente disponível.',
      },
    },
  },
  {
    slug: 'elevenlabs',
    name: 'ElevenLabs',
    description: {
      fr: 'Synthèse vocale IA ultra-réaliste. Voix off, doublage, podcasts multilingues.',
      en: 'Ultra-realistic AI voice synthesis. Voiceovers, dubbing, multilingual podcasts.',
      lb: 'Ultra-realistesch KI-Stëmmsynthese. Voiceovers, Synchroniséierung, méisproocheg Podcasts.',
      de: 'Ultra-realistische KI-Sprachsynthese. Voiceover, Synchronisation, mehrsprachige Podcasts.',
      it: 'Sintesi vocale IA ultra-realistica. Voiceover, doppiaggio, podcast multilingue.',
      pt: 'Síntese vocal IA ultra-realista. Voiceovers, dobragem, podcasts multilingues.',
    },
    longDescription: {
      fr: "ElevenLabs est une plateforme de synthèse vocale IA ultra-réaliste, fondée par des Européens (Pologne). Idéale pour les voix off, le doublage et les podcasts multilingues. Résidence de données UE disponible pour les clients Enterprise.",
      en: 'ElevenLabs is an ultra-realistic AI voice synthesis platform, founded by Europeans (Poland). Ideal for voiceovers, dubbing and multilingual podcasts. EU data residency available for Enterprise customers.',
      lb: 'ElevenLabs ass eng ultra-realistesch KI-Stëmmsynthese-Plattform, gegrënnt vu Europäer (Polen). Ideal fir Voiceovers, Synchroniséierung a méisproocheg Podcasts.',
      de: 'ElevenLabs ist eine ultra-realistische KI-Sprachsynthese-Plattform, gegründet von Europäern (Polen). Ideal für Voiceovers, Synchronisation und mehrsprachige Podcasts.',
      it: "ElevenLabs è una piattaforma di sintesi vocale IA ultra-realistica, fondata da europei (Polonia). Ideale per voiceover, doppiaggio e podcast multilingue.",
      pt: 'ElevenLabs é uma plataforma de síntese vocal IA ultra-realista, fundada por europeus (Polónia). Ideal para voiceovers, dobragem e podcasts multilingues.',
    },
    category: 'content',
    url: 'https://elevenlabs.io',
    tags: ['Voice', 'Audio'],
    free: true,
    pricing: {
      fr: 'Gratuit (10 min/mois) · Starter : 5 $/mois · Creator : 22 $/mois · Pro : 99 $/mois',
      en: 'Free (10 min/mo) · Starter: $5/mo · Creator: $22/mo · Pro: $99/mo',
      lb: 'Gratis (10 Min/Mount) · Starter: 5 $/Mount · Creator: 22 $/Mount · Pro: 99 $/Mount',
      de: 'Kostenlos (10 Min/Monat) · Starter: 5 $/Monat · Creator: 22 $/Monat · Pro: 99 $/Monat',
      it: 'Gratuito (10 min/mese) · Starter: 5 $/mese · Creator: 22 $/mese · Pro: 99 $/mese',
      pt: 'Gratuito (10 min/mês) · Starter: 5 $/mês · Creator: 22 $/mês · Pro: 99 $/mês',
    },
    vendor: 'ElevenLabs',
    founded: '2022',
    headquarters: 'New York, USA / London, UK',
    euCompliance: {
      gdprCompliant: true,
      euAiActReady: false,
      dataLocation: 'US, Netherlands, Singapore',
      hasEuDataResidency: true,
      dpaAvailable: true,
      certifications: ['SOC 2 Type II', 'ISO 27001', 'PCI DSS Level 1'],
      complianceNote: {
        fr: "Racines européennes (fondateurs polonais, bureaux à Londres et Varsovie). Certifié EU-US Data Privacy Framework. Résidence de données UE pour Enterprise. Mode Zero Retention disponible.",
        en: 'European roots (Polish founders, offices in London and Warsaw). Certified under EU-US Data Privacy Framework. EU data residency for Enterprise. Zero Retention Mode available.',
        lb: 'Europäesch Wuerzelen (polnesch Grënner, Büroe vu London a Warschau). Zertifizéiert ënnert EU-US Data Privacy Framework.',
        de: 'Europäische Wurzeln (polnische Gründer, Büros in London und Warschau). Zertifiziert unter EU-US Data Privacy Framework.',
        it: 'Radici europee (fondatori polacchi, uffici a Londra e Varsavia). Certificato EU-US Data Privacy Framework.',
        pt: 'Raízes europeias (fundadores polacos, escritórios em Londres e Varsóvia). Certificado EU-US Data Privacy Framework.',
      },
    },
  },
  {
    slug: 'zapier-ai',
    name: 'Zapier AI',
    description: {
      fr: "Automatisation de workflows avec l'IA. Connectez vos apps et automatisez vos tâches répétitives.",
      en: 'AI-powered workflow automation. Connect your apps and automate repetitive tasks.',
      lb: 'KI-gestäerkt Workflow-Automatisatioun. Verbënnt Är Apps a automatiséiert repetitiv Aufgaben.',
      de: 'KI-gestützte Workflow-Automatisierung. Verbinden Sie Ihre Apps und automatisieren Sie Routineaufgaben.',
      it: "Automazione workflow con IA. Collegate le vostre app e automatizzate i compiti ripetitivi.",
      pt: 'Automação de workflows com IA. Conecte as suas apps e automatize tarefas repetitivas.',
    },
    longDescription: {
      fr: "Zapier AI automatise les workflows entre plus de 6 000 applications. Connectez vos outils (CRM, email, facturation) et automatisez les tâches répétitives grâce à l'IA. DPA auto-intégré dans les conditions d'utilisation.",
      en: 'Zapier AI automates workflows between 6,000+ applications. Connect your tools (CRM, email, invoicing) and automate repetitive tasks with AI. DPA auto-incorporated into Terms of Service.',
      lb: "Zapier AI automatiséiert Workflows tëschent méi wéi 6.000 Applikatiounen. Verbënnt Är Tools (CRM, Email, Facturatioun) an automatiséiert repetitiv Aufgaben mat KI.",
      de: 'Zapier AI automatisiert Workflows zwischen über 6.000 Anwendungen. Verbinden Sie Ihre Tools (CRM, E-Mail, Rechnungsstellung) und automatisieren Sie Routineaufgaben mit KI.',
      it: "Zapier AI automatizza i workflow tra oltre 6.000 applicazioni. Collegate i vostri strumenti e automatizzate i compiti ripetitivi con l'IA.",
      pt: 'Zapier AI automatiza workflows entre mais de 6.000 aplicações. Conecte as suas ferramentas e automatize tarefas repetitivas com IA.',
    },
    category: 'productivity',
    url: 'https://zapier.com',
    tags: ['Automation', 'Integration'],
    free: true,
    pricing: {
      fr: 'Gratuit (100 tâches/mois) · Starter : 19,99 $/mois · Professional : 49 $/mois',
      en: 'Free (100 tasks/mo) · Starter: $19.99/mo · Professional: $49/mo',
      lb: 'Gratis (100 Aufgaben/Mount) · Starter: 19,99 $/Mount · Professional: 49 $/Mount',
      de: 'Kostenlos (100 Aufgaben/Monat) · Starter: 19,99 $/Monat · Professional: 49 $/Monat',
      it: 'Gratuito (100 compiti/mese) · Starter: 19,99 $/mese · Professional: 49 $/mese',
      pt: 'Gratuito (100 tarefas/mês) · Starter: 19,99 $/mês · Professional: 49 $/mês',
    },
    vendor: 'Zapier',
    founded: '2011',
    headquarters: 'San Francisco, USA',
    euCompliance: {
      gdprCompliant: true,
      euAiActReady: false,
      dataLocation: 'US (AWS)',
      hasEuDataResidency: false,
      dpaAvailable: true,
      certifications: ['SOC 2 Type II', 'SOC 3'],
      complianceNote: {
        fr: "Conforme RGPD avec DPA incluant des CCT. Certifié EU-US DPF. Représentant UE désigné (DP-Dock GmbH, Hambourg). Données Enterprise non utilisées pour l'entraînement IA.",
        en: 'GDPR compliant with DPA including SCCs. EU-US DPF certified. EU representative appointed (DP-Dock GmbH, Hamburg). Enterprise data not used for AI training.',
        lb: 'RGPD-konform mat DPA inklusive CCT. EU-US DPF zertifizéiert. EU-Vertrieder ernannt.',
        de: 'DSGVO-konform mit AVV einschließlich SCC. EU-US DPF zertifiziert. EU-Vertreter ernannt (DP-Dock GmbH, Hamburg).',
        it: 'Conforme GDPR con DPA che include SCC. Certificato EU-US DPF. Rappresentante UE designato.',
        pt: 'Conforme RGPD com DPA incluindo CCT. Certificado EU-US DPF. Representante UE designado.',
      },
    },
  },
  {
    slug: 'notion-ai',
    name: 'Notion AI',
    description: {
      fr: 'IA intégrée à Notion pour rédiger, résumer et organiser vos documents et projets.',
      en: 'AI integrated into Notion to write, summarize and organize your documents and projects.',
      lb: 'KI integréiert an Notion fir Dokumenter a Projete ze schreiwen, zesummefaassen an z\'organiséieren.',
      de: 'KI in Notion integriert zum Schreiben, Zusammenfassen und Organisieren Ihrer Dokumente und Projekte.',
      it: 'IA integrata in Notion per scrivere, riassumere e organizzare documenti e progetti.',
      pt: 'IA integrada no Notion para escrever, resumir e organizar documentos e projetos.',
    },
    longDescription: {
      fr: "Notion AI est l'intelligence artificielle intégrée directement dans Notion. Elle vous aide à rédiger, résumer, organiser et rechercher dans vos documents et projets. Résidence de données UE disponible. Conforme HIPAA pour Enterprise.",
      en: 'Notion AI is artificial intelligence integrated directly into Notion. It helps you write, summarize, organize and search through your documents and projects. EU data residency available. HIPAA compliant for Enterprise.',
      lb: 'Notion AI ass KI direkt an Notion integréiert. Et hëlleft Iech ze schreiwen, zesummefaassen, organiséieren a sichen an Ären Dokumenter a Projeten.',
      de: 'Notion AI ist KI direkt in Notion integriert. Sie hilft beim Schreiben, Zusammenfassen, Organisieren und Durchsuchen Ihrer Dokumente und Projekte.',
      it: "Notion AI è l'intelligenza artificiale integrata direttamente in Notion. Vi aiuta a scrivere, riassumere, organizzare e cercare nei vostri documenti e progetti.",
      pt: 'Notion AI é inteligência artificial integrada diretamente no Notion. Ajuda a escrever, resumir, organizar e pesquisar nos seus documentos e projetos.',
    },
    category: 'productivity',
    url: 'https://notion.so',
    tags: ['Docs', 'Projects'],
    free: true,
    pricing: {
      fr: 'Gratuit (limité) · Plus : 10 $/mois · Business : 18 $/mois · Enterprise : sur devis · IA : +10 $/mois',
      en: 'Free (limited) · Plus: $10/mo · Business: $18/mo · Enterprise: custom · AI: +$10/mo',
      lb: 'Gratis (limitéiert) · Plus: 10 $/Mount · Business: 18 $/Mount · Enterprise: op Ufro · AI: +10 $/Mount',
      de: 'Kostenlos (begrenzt) · Plus: 10 $/Monat · Business: 18 $/Monat · Enterprise: auf Anfrage · AI: +10 $/Monat',
      it: 'Gratuito (limitato) · Plus: 10 $/mese · Business: 18 $/mese · Enterprise: su richiesta · AI: +10 $/mese',
      pt: 'Gratuito (limitado) · Plus: 10 $/mês · Business: 18 $/mês · Enterprise: sob consulta · AI: +10 $/mês',
    },
    vendor: 'Notion Labs',
    founded: '2016',
    headquarters: 'San Francisco, USA',
    euCompliance: {
      gdprCompliant: true,
      euAiActReady: false,
      dataLocation: 'US (AWS); EU data residency available',
      hasEuDataResidency: true,
      dpaAvailable: true,
      certifications: ['SOC 2 Type II', 'ISO 27001:2022', 'ISO 27701', 'ISO 27017', 'ISO 27018'],
      complianceNote: {
        fr: "Conforme RGPD avec DPO désigné. Résidence de données UE disponible. Les workspaces Enterprise bénéficient d'une rétention zéro avec les fournisseurs de LLM. Conforme HIPAA avec BAA pour Enterprise.",
        en: 'GDPR compliant with appointed DPO. EU data residency available. Enterprise workspaces benefit from zero data retention with LLM providers. HIPAA compliant with BAA for Enterprise.',
        lb: 'RGPD-konform mat ernanntem DPO. EU-Datenresidenz verfügbar. Enterprise Workspaces profitéiere vun Null-Datenretentioun.',
        de: 'DSGVO-konform mit ernanntem DSB. EU-Datenresidenz verfügbar. Enterprise-Workspaces profitieren von Null-Datenaufbewahrung bei LLM-Anbietern.',
        it: "Conforme GDPR con DPO designato. Residenza dati UE disponibile. I workspace Enterprise beneficiano di zero retention con i fornitori LLM.",
        pt: 'Conforme RGPD com DPO designado. Residência de dados UE disponível. Workspaces Enterprise beneficiam de zero retenção com fornecedores LLM.',
      },
    },
  },
  {
    slug: 'otter-ai',
    name: 'Otter.ai',
    description: {
      fr: 'Transcription automatique de réunions et interviews. Notes IA en temps réel.',
      en: 'Automatic meeting and interview transcription. Real-time AI notes.',
      lb: 'Automatesch Transkriptioun vu Reuniounen an Interviewen. Echtzäit KI-Notizen.',
      de: 'Automatische Transkription von Meetings und Interviews. KI-Notizen in Echtzeit.',
      it: 'Trascrizione automatica di riunioni e interviste. Note IA in tempo reale.',
      pt: 'Transcrição automática de reuniões e entrevistas. Notas IA em tempo real.',
    },
    longDescription: {
      fr: "Otter.ai transcrit automatiquement vos réunions et interviews en temps réel. Notes IA, résumés, recherche et partage. Toutes les données sont stockées aux US, sans option de résidence UE.",
      en: 'Otter.ai automatically transcribes your meetings and interviews in real-time. AI notes, summaries, search and sharing. All data stored in the US, with no EU residency option.',
      lb: 'Otter.ai transkribéiert automatesch Är Reuniounen an Interviewen an Echtzäit. KI-Notizen, Zesummefaassungen, Sich a Partage.',
      de: 'Otter.ai transkribiert automatisch Ihre Meetings und Interviews in Echtzeit. KI-Notizen, Zusammenfassungen, Suche und Teilen.',
      it: 'Otter.ai trascrive automaticamente le vostre riunioni e interviste in tempo reale. Note IA, riassunti, ricerca e condivisione.',
      pt: 'Otter.ai transcreve automaticamente as suas reuniões e entrevistas em tempo real. Notas IA, resumos, pesquisa e partilha.',
    },
    category: 'productivity',
    url: 'https://otter.ai',
    tags: ['Transcription', 'Meetings'],
    free: true,
    pricing: {
      fr: 'Gratuit (300 min/mois) · Pro : 16,99 $/mois · Business : 30 $/mois · Enterprise : sur devis',
      en: 'Free (300 min/mo) · Pro: $16.99/mo · Business: $30/mo · Enterprise: custom pricing',
      lb: 'Gratis (300 Min/Mount) · Pro: 16,99 $/Mount · Business: 30 $/Mount · Enterprise: op Ufro',
      de: 'Kostenlos (300 Min/Monat) · Pro: 16,99 $/Monat · Business: 30 $/Monat · Enterprise: auf Anfrage',
      it: 'Gratuito (300 min/mese) · Pro: 16,99 $/mese · Business: 30 $/mese · Enterprise: su richiesta',
      pt: 'Gratuito (300 min/mês) · Pro: 16,99 $/mês · Business: 30 $/mês · Enterprise: sob consulta',
    },
    vendor: 'Otter.ai (AISense)',
    founded: '2016',
    headquarters: 'Mountain View, USA',
    euCompliance: {
      gdprCompliant: 'partial',
      euAiActReady: false,
      dataLocation: 'US (AWS US-West)',
      hasEuDataResidency: false,
      dpaAvailable: true,
      certifications: ['SOC 2 Type II', 'ISO 27001'],
      complianceNote: {
        fr: "Fonctionnalités compatibles RGPD mais toutes les données stockées aux US. Certifié EU-US DPF. Sur les plans non-Enterprise, Otter.ai agit comme responsable de traitement (risque RGPD important).",
        en: 'GDPR-capable features but all data stored in the US. EU-US DPF certified. On non-Enterprise plans, Otter.ai acts as data controller (significant GDPR risk).',
        lb: 'RGPD-fäeg Funktiounen awer all Daten an den US gespäichert. EU-US DPF zertifizéiert.',
        de: 'DSGVO-fähige Funktionen, aber alle Daten in den USA gespeichert. EU-US DPF zertifiziert.',
        it: 'Funzionalità compatibili GDPR ma tutti i dati archiviati negli USA. Certificato EU-US DPF.',
        pt: 'Funcionalidades compatíveis RGPD mas todos os dados armazenados nos EUA. Certificado EU-US DPF.',
      },
    },
  },
  {
    slug: 'julius-ai',
    name: 'Julius AI',
    description: {
      fr: "Analyse de données par l'IA. Importez vos fichiers et obtenez des insights instantanés.",
      en: 'AI-powered data analysis. Import your files and get instant insights.',
      lb: 'KI-gestäerkt Datenanalyse. Importéiert Är Fichieren a kritt direkt Insights.',
      de: 'KI-gestützte Datenanalyse. Importieren Sie Ihre Dateien und erhalten Sie sofortige Insights.',
      it: "Analisi dati con IA. Importate i vostri file e ottenete insights istantanei.",
      pt: 'Análise de dados com IA. Importe os seus ficheiros e obtenha insights instantâneos.',
    },
    longDescription: {
      fr: "Julius AI analyse vos données grâce à l'intelligence artificielle. Importez vos fichiers (CSV, Excel, etc.) et obtenez des insights, graphiques et analyses instantanément. Isolation des données clients.",
      en: 'Julius AI analyzes your data with artificial intelligence. Import your files (CSV, Excel, etc.) and get instant insights, charts and analysis. Customer data isolation enforced.',
      lb: 'Julius AI analyséiert Är Daten mat KI. Importéiert Är Fichieren (CSV, Excel, etc.) a kritt direkt Insights, Grafiken an Analysen.',
      de: 'Julius AI analysiert Ihre Daten mit KI. Importieren Sie Ihre Dateien (CSV, Excel, etc.) und erhalten Sie sofortige Insights, Diagramme und Analysen.',
      it: "Julius AI analizza i vostri dati con l'IA. Importate i vostri file (CSV, Excel, ecc.) e ottenete insights, grafici e analisi istantaneamente.",
      pt: 'Julius AI analisa os seus dados com IA. Importe os seus ficheiros (CSV, Excel, etc.) e obtenha insights, gráficos e análises instantaneamente.',
    },
    category: 'analytics',
    url: 'https://julius.ai',
    tags: ['Data', 'Insights'],
    free: true,
    pricing: {
      fr: 'Gratuit (limité) · Pro : 20 $/mois · Teams : sur devis',
      en: 'Free (limited) · Pro: $20/mo · Teams: custom pricing',
      lb: 'Gratis (limitéiert) · Pro: 20 $/Mount · Teams: op Ufro',
      de: 'Kostenlos (begrenzt) · Pro: 20 $/Monat · Teams: auf Anfrage',
      it: 'Gratuito (limitato) · Pro: 20 $/mese · Teams: su richiesta',
      pt: 'Gratuito (limitado) · Pro: 20 $/mês · Teams: sob consulta',
    },
    vendor: 'Julius AI',
    founded: '2023',
    headquarters: 'San Francisco, USA',
    euCompliance: {
      gdprCompliant: true,
      euAiActReady: false,
      dataLocation: 'US (San Francisco)',
      hasEuDataResidency: false,
      dpaAvailable: true,
      certifications: ['SOC 2 Type II'],
      complianceNote: {
        fr: "Conforme RGPD avec représentants UE/UK désignés (Art. 27 RGPD). DPA avec CCT disponible. Isolation des données clients. Données chiffrées en transit et au repos.",
        en: 'GDPR compliant with appointed EU/UK representatives (Art. 27 GDPR). DPA with SCCs available. Customer data isolation. Encrypted in transit and at rest.',
        lb: 'RGPD-konform mat ernannten EU/UK-Vertrieder (Art. 27 RGPD). DPA mat CCT verfügbar.',
        de: 'DSGVO-konform mit ernannten EU/UK-Vertretern (Art. 27 DSGVO). AVV mit SCC verfügbar.',
        it: 'Conforme GDPR con rappresentanti UE/UK designati (Art. 27 GDPR). DPA con SCC disponibile.',
        pt: 'Conforme RGPD com representantes UE/UK designados (Art. 27 RGPD). DPA com CCT disponível.',
      },
    },
  },
  {
    slug: 'rows-ai',
    name: 'Rows AI',
    description: {
      fr: 'Tableur avec IA intégrée. Analysez et visualisez vos données avec des prompts naturels.',
      en: 'Spreadsheet with built-in AI. Analyze and visualize data with natural prompts.',
      lb: 'Tabellekalkul mat integréierter KI. Analyséiert a visualiséiert Daten mat natierleche Prompts.',
      de: 'Tabellenkalkulation mit integrierter KI. Analysieren und visualisieren Sie Daten mit natürlichen Prompts.',
      it: 'Foglio di calcolo con IA integrata. Analizzate e visualizzate dati con prompt naturali.',
      pt: 'Folha de cálculo com IA integrada. Analise e visualize dados com prompts naturais.',
    },
    longDescription: {
      fr: "Rows AI est un tableur avec IA intégrée, basé en Allemagne. Analysez et visualisez vos données avec des prompts en langage naturel. Entreprise native de l'UE, soumise aux régulations allemandes strictes.",
      en: 'Rows AI is a spreadsheet with built-in AI, based in Germany. Analyze and visualize data with natural language prompts. EU-native company subject to strict German data protection regulations.',
      lb: 'Rows AI ass en Tabellekalkul mat integréierter KI, baséiert an Däitschland. Analyséiert a visualiséiert Daten mat natierleche Sprooch-Prompts. EU-nativ Firma.',
      de: 'Rows AI ist eine Tabellenkalkulation mit integrierter KI, ansässig in Deutschland. Analysieren und visualisieren Sie Daten mit natürlichsprachlichen Prompts. EU-natives Unternehmen.',
      it: "Rows AI è un foglio di calcolo con IA integrata, con sede in Germania. Analizzate e visualizzate dati con prompt in linguaggio naturale. Azienda nativa dell'UE.",
      pt: 'Rows AI é uma folha de cálculo com IA integrada, sediada na Alemanha. Analise e visualize dados com prompts em linguagem natural. Empresa nativa da UE.',
    },
    category: 'analytics',
    url: 'https://rows.com',
    tags: ['Spreadsheet', 'Charts'],
    free: true,
    pricing: {
      fr: 'Gratuit (limité) · Pro : 59 $/mois · Enterprise : sur devis',
      en: 'Free (limited) · Pro: $59/mo · Enterprise: custom pricing',
      lb: 'Gratis (limitéiert) · Pro: 59 $/Mount · Enterprise: op Ufro',
      de: 'Kostenlos (begrenzt) · Pro: 59 $/Monat · Enterprise: auf Anfrage',
      it: 'Gratuito (limitato) · Pro: 59 $/mese · Enterprise: su richiesta',
      pt: 'Gratuito (limitado) · Pro: 59 $/mês · Enterprise: sob consulta',
    },
    vendor: 'Rows GmbH',
    founded: '2017',
    headquarters: 'Berlin, Germany',
    euCompliance: {
      gdprCompliant: true,
      euAiActReady: false,
      dataLocation: 'EU (Germany)',
      hasEuDataResidency: true,
      dpaAvailable: true,
      certifications: [],
      complianceNote: {
        fr: "Entreprise native de l'UE (Rows GmbH, Berlin). Soumise aux régulations RGPD allemandes strictes. DPO externe désigné. Audits RGPD annuels par les autorités allemandes. Re-certification bisannuelle.",
        en: 'EU-native company (Rows GmbH, Berlin). Subject to strict German GDPR regulations. External DPO appointed. Annual GDPR audits by German authorities. Biennial re-certification.',
        lb: "EU-nativ Firma (Rows GmbH, Berlin). Ënnerworf un streng däitsch RGPD-Regulatiounen. Externen DPO ernannt.",
        de: 'EU-natives Unternehmen (Rows GmbH, Berlin). Unterliegt strengen deutschen DSGVO-Vorschriften. Externer DSB bestellt. Jährliche DSGVO-Audits.',
        it: "Azienda nativa dell'UE (Rows GmbH, Berlino). Soggetta alle rigide normative GDPR tedesche. DPO esterno designato.",
        pt: 'Empresa nativa da UE (Rows GmbH, Berlim). Sujeita às rigorosas regulamentações RGPD alemãs. DPO externo designado.',
      },
    },
  },
  {
    slug: 'monkeylearn',
    name: 'MonkeyLearn',
    description: {
      fr: "Analyse de texte par IA. Classification, analyse de sentiments et extraction d'informations.",
      en: 'AI text analysis. Classification, sentiment analysis and information extraction.',
      lb: 'KI-Textanalyse. Klassifikatioun, Sentimentanalyse an Informatiounsextraktioun.',
      de: 'KI-Textanalyse. Klassifikation, Sentiment-Analyse und Informationsextraktion.',
      it: "Analisi testo con IA. Classificazione, analisi del sentimento ed estrazione informazioni.",
      pt: 'Análise de texto com IA. Classificação, análise de sentimento e extração de informação.',
    },
    longDescription: {
      fr: "MonkeyLearn (acquis par Medallia) est une plateforme d'analyse de texte par IA. Classification de texte, analyse de sentiments, extraction d'entités. Les certifications de la société mère Medallia peuvent s'appliquer.",
      en: 'MonkeyLearn (acquired by Medallia) is an AI text analysis platform. Text classification, sentiment analysis, entity extraction. Parent company Medallia certifications may apply.',
      lb: 'MonkeyLearn (opkaaft vun Medallia) ass eng KI-Textanalyse-Plattform. Textklassifikatioun, Sentimentanalyse, Entitéitsextraktioun.',
      de: 'MonkeyLearn (von Medallia übernommen) ist eine KI-Textanalyseplattform. Textklassifikation, Sentiment-Analyse, Entitätsextraktion.',
      it: "MonkeyLearn (acquisito da Medallia) è una piattaforma di analisi testo IA. Classificazione testi, analisi sentiment, estrazione entità.",
      pt: 'MonkeyLearn (adquirido pela Medallia) é uma plataforma de análise de texto IA. Classificação de texto, análise de sentimento, extração de entidades.',
    },
    category: 'analytics',
    url: 'https://monkeylearn.com',
    tags: ['NLP', 'Sentiment'],
    free: true,
    pricing: {
      fr: 'Gratuit (300 requêtes/mois) · Team : 299 $/mois · Business : 999 $/mois · Enterprise : sur devis',
      en: 'Free (300 queries/mo) · Team: $299/mo · Business: $999/mo · Enterprise: custom pricing',
      lb: 'Gratis (300 Ufroen/Mount) · Team: 299 $/Mount · Business: 999 $/Mount · Enterprise: op Ufro',
      de: 'Kostenlos (300 Anfragen/Monat) · Team: 299 $/Monat · Business: 999 $/Monat · Enterprise: auf Anfrage',
      it: 'Gratuito (300 richieste/mese) · Team: 299 $/mese · Business: 999 $/mese · Enterprise: su richiesta',
      pt: 'Gratuito (300 consultas/mês) · Team: 299 $/mês · Business: 999 $/mês · Enterprise: sob consulta',
    },
    vendor: 'Medallia (MonkeyLearn)',
    founded: '2014',
    headquarters: 'San Francisco, USA',
    euCompliance: {
      gdprCompliant: 'partial',
      euAiActReady: false,
      dataLocation: 'US (Medallia infrastructure)',
      hasEuDataResidency: false,
      dpaAvailable: false,
      certifications: ['SOC 2 Type II (via Medallia)', 'ISO 27001 (via Medallia)'],
      complianceNote: {
        fr: "Conformité RGPD via la société mère Medallia. Pas de DPA autonome pour MonkeyLearn. Certifications Medallia (SOC 2, ISO 27001) peuvent ne pas couvrir entièrement MonkeyLearn.",
        en: 'GDPR compliance via parent company Medallia. No standalone MonkeyLearn DPA. Medallia certifications (SOC 2, ISO 27001) may not fully cover MonkeyLearn.',
        lb: 'RGPD-Konformitéit iwwer Muttergesellschaft Medallia. Keen eegenen DPA fir MonkeyLearn.',
        de: 'DSGVO-Konformität über Muttergesellschaft Medallia. Keine eigenständige AVV für MonkeyLearn.',
        it: "Conformità GDPR tramite la società madre Medallia. Nessun DPA autonomo per MonkeyLearn.",
        pt: 'Conformidade RGPD via empresa-mãe Medallia. Nenhum DPA autónomo para MonkeyLearn.',
      },
    },
  },
  {
    slug: 'midjourney',
    name: 'Midjourney',
    description: {
      fr: "Génération d'images IA haut de gamme. Créez des visuels professionnels à partir de descriptions.",
      en: 'High-end AI image generation. Create professional visuals from text descriptions.',
      lb: 'Héichwertig KI-Bildgeneratioun. Erstellt professionell Visuellen aus Textbeschreiwungen.',
      de: 'Hochwertige KI-Bildgenerierung. Erstellen Sie professionelle Visuals aus Textbeschreibungen.',
      it: "Generazione immagini IA di alta gamma. Create visual professionali da descrizioni testuali.",
      pt: 'Geração de imagens IA de alta gama. Crie visuais profissionais a partir de descrições.',
    },
    longDescription: {
      fr: "Midjourney est un générateur d'images IA haut de gamme. Attention : lacunes importantes en matière de conformité UE. Pas de DPA, pas de certifications de sécurité, toutes les images sont publiques par défaut sauf le plan le plus cher.",
      en: 'Midjourney is a high-end AI image generator. Warning: significant EU compliance gaps. No DPA, no security certifications, all images public by default except on the most expensive plan.',
      lb: 'Midjourney ass en héichwäertegen KI-Bildgenerator. Opgepasst: bedeitend EU-Konformitéitslücken. Keen DPA, keng Sécherheetszertifizéierungen.',
      de: 'Midjourney ist ein hochwertiger KI-Bildgenerator. Achtung: erhebliche EU-Compliance-Lücken. Keine AVV, keine Sicherheitszertifizierungen.',
      it: "Midjourney è un generatore di immagini IA di alta gamma. Attenzione: lacune significative nella conformità UE. Nessun DPA, nessuna certificazione di sicurezza.",
      pt: 'Midjourney é um gerador de imagens IA de alta gama. Atenção: lacunas significativas na conformidade UE. Sem DPA, sem certificações de segurança.',
    },
    category: 'creative',
    url: 'https://midjourney.com',
    tags: ['Images', 'Design'],
    free: false,
    pricing: {
      fr: 'Basic : 10 $/mois · Standard : 30 $/mois · Pro : 60 $/mois · Mega : 120 $/mois',
      en: 'Basic: $10/mo · Standard: $30/mo · Pro: $60/mo · Mega: $120/mo',
      lb: 'Basic: 10 $/Mount · Standard: 30 $/Mount · Pro: 60 $/Mount · Mega: 120 $/Mount',
      de: 'Basic: 10 $/Monat · Standard: 30 $/Monat · Pro: 60 $/Monat · Mega: 120 $/Monat',
      it: 'Basic: 10 $/mese · Standard: 30 $/mese · Pro: 60 $/mese · Mega: 120 $/mese',
      pt: 'Basic: 10 $/mês · Standard: 30 $/mês · Pro: 60 $/mês · Mega: 120 $/mês',
    },
    vendor: 'Midjourney',
    founded: '2021',
    headquarters: 'San Francisco, USA',
    euCompliance: {
      gdprCompliant: false,
      euAiActReady: false,
      dataLocation: 'US',
      hasEuDataResidency: false,
      dpaAvailable: false,
      certifications: [],
      complianceNote: {
        fr: "Lacunes importantes de conformité. Pas de DPA, pas de certifications de sécurité, pas de résidence de données UE. Images publiques par défaut sauf plan Pro (60 $/mois). Plaintes RGPD déposées. Non recommandé pour un usage professionnel réglementé dans l'UE.",
        en: 'Significant compliance gaps. No DPA, no security certifications, no EU data residency. Images public by default except Pro plan ($60/mo). GDPR complaints filed. Not recommended for regulated professional use in the EU.',
        lb: 'Bedeitend Konformitéitslücken. Keen DPA, keng Sécherheetszertifizéierungen, keng EU-Datenresidenz.',
        de: 'Erhebliche Compliance-Lücken. Keine AVV, keine Sicherheitszertifizierungen, keine EU-Datenresidenz.',
        it: "Lacune significative di conformità. Nessun DPA, nessuna certificazione di sicurezza, nessuna residenza dati UE.",
        pt: 'Lacunas significativas de conformidade. Sem DPA, sem certificações de segurança, sem residência de dados UE.',
      },
    },
  },
  {
    slug: 'canva-ai',
    name: 'Canva AI',
    description: {
      fr: "Design graphique assisté par l'IA. Présentations, posts sociaux, logos et supports marketing.",
      en: 'AI-assisted graphic design. Presentations, social posts, logos and marketing materials.',
      lb: 'KI-ënnerstëtzt grafesch Design. Presentatiounen, sozial Posts, Logoen a Marketingmaterial.',
      de: 'KI-unterstütztes Grafikdesign. Präsentationen, Social Posts, Logos und Marketingmaterial.',
      it: 'Design grafico assistito da IA. Presentazioni, post social, loghi e materiale marketing.',
      pt: 'Design gráfico assistido por IA. Apresentações, posts sociais, logótipos e materiais de marketing.',
    },
    longDescription: {
      fr: "Canva AI offre des fonctionnalités de design graphique assisté par IA. Présentations, posts sociaux, logos et supports marketing. Résidence de données UE disponible pour les plans Enterprise. Canva Shield offre des contrôles de gouvernance IA.",
      en: 'Canva AI offers AI-assisted graphic design features. Presentations, social posts, logos and marketing materials. EU data residency available for Enterprise plans. Canva Shield provides AI governance controls.',
      lb: 'Canva AI bitt KI-ënnerstëtzt grafesch Design Funktiounen. Presentatiounen, sozial Posts, Logoen a Marketingmaterial. EU-Datenresidenz fir Enterprise Plangen.',
      de: 'Canva AI bietet KI-unterstützte Grafikdesign-Funktionen. Präsentationen, Social Posts, Logos und Marketingmaterial. EU-Datenresidenz für Enterprise-Pläne.',
      it: "Canva AI offre funzionalità di design grafico assistito da IA. Presentazioni, post social, loghi e materiale marketing. Residenza dati UE per piani Enterprise.",
      pt: 'Canva AI oferece funcionalidades de design gráfico assistido por IA. Apresentações, posts sociais, logótipos e materiais de marketing. Residência de dados UE para planos Enterprise.',
    },
    category: 'creative',
    url: 'https://canva.com',
    tags: ['Design', 'Templates'],
    free: true,
    pricing: {
      fr: 'Gratuit (limité) · Pro : 12,99 $/mois · Teams : 14,99 $/mois · Enterprise : sur devis',
      en: 'Free (limited) · Pro: $12.99/mo · Teams: $14.99/mo · Enterprise: custom pricing',
      lb: 'Gratis (limitéiert) · Pro: 12,99 $/Mount · Teams: 14,99 $/Mount · Enterprise: op Ufro',
      de: 'Kostenlos (begrenzt) · Pro: 12,99 $/Monat · Teams: 14,99 $/Monat · Enterprise: auf Anfrage',
      it: 'Gratuito (limitato) · Pro: 12,99 $/mese · Teams: 14,99 $/mese · Enterprise: su richiesta',
      pt: 'Gratuito (limitado) · Pro: 12,99 $/mês · Teams: 14,99 $/mês · Enterprise: sob consulta',
    },
    vendor: 'Canva Pty Ltd',
    founded: '2013',
    headquarters: 'Sydney, Australia',
    euCompliance: {
      gdprCompliant: true,
      euAiActReady: false,
      dataLocation: 'US (default, AWS); EU for Enterprise',
      hasEuDataResidency: true,
      dpaAvailable: true,
      certifications: ['SOC 2 Type II', 'ISO 27001'],
      complianceNote: {
        fr: "Conforme RGPD avec DPA auto-intégré pour Business incluant CCT UE. Résidence de données UE pour Enterprise, Campus et District. Canva Shield offre des contrôles de gouvernance IA pour les entreprises.",
        en: 'GDPR compliant with DPA auto-incorporated for Business including EU SCCs. EU data residency for Enterprise, Campus and District plans. Canva Shield offers AI governance controls.',
        lb: 'RGPD-konform mat DPA automatesch integréiert fir Business inklusive EU-CCT. EU-Datenresidenz fir Enterprise.',
        de: 'DSGVO-konform mit automatisch integrierter AVV für Business einschließlich EU-SCC. EU-Datenresidenz für Enterprise.',
        it: "Conforme GDPR con DPA auto-incorporato per Business incluso SCC UE. Residenza dati UE per Enterprise.",
        pt: 'Conforme RGPD com DPA auto-incorporado para Business incluindo CCT UE. Residência de dados UE para Enterprise.',
      },
    },
  },
  {
    slug: 'runway',
    name: 'Runway',
    description: {
      fr: 'Génération et édition vidéo par IA. Effets spéciaux, animations et production vidéo.',
      en: 'AI video generation and editing. Special effects, animations and video production.',
      lb: 'KI-Videogeneratioun an -Editioun. Spezialeffekter, Animatiounen a Videoproduktioun.',
      de: 'KI-Videogenerierung und -Bearbeitung. Spezialeffekte, Animationen und Videoproduktion.',
      it: 'Generazione e editing video con IA. Effetti speciali, animazioni e produzione video.',
      pt: 'Geração e edição de vídeo com IA. Efeitos especiais, animações e produção vídeo.',
    },
    longDescription: {
      fr: "Runway est une plateforme de génération et d'édition vidéo par IA. Effets spéciaux, animations et production vidéo. Tous les assets sont privés par défaut. La conformité RGPD est décrite comme \"readiness\" plutôt que certification complète.",
      en: 'Runway is an AI video generation and editing platform. Special effects, animations and video production. All assets private by default. GDPR compliance described as "readiness" rather than full certification.',
      lb: 'Runway ass eng KI-Videogeneratioun an -Editiounsplattform. Spezialeffekter, Animatiounen a Videoproduktioun. All Assets privat par défaut.',
      de: 'Runway ist eine KI-Videogenerierungs- und -Bearbeitungsplattform. Spezialeffekte, Animationen und Videoproduktion. Alle Assets standardmäßig privat.',
      it: "Runway è una piattaforma di generazione e editing video con IA. Effetti speciali, animazioni e produzione video. Tutti gli asset privati per default.",
      pt: 'Runway é uma plataforma de geração e edição de vídeo com IA. Efeitos especiais, animações e produção vídeo. Todos os assets privados por defeito.',
    },
    category: 'creative',
    url: 'https://runwayml.com',
    tags: ['Video', 'Effects'],
    free: true,
    pricing: {
      fr: 'Gratuit (125 crédits) · Standard : 12 $/mois · Pro : 28 $/mois · Unlimited : 76 $/mois',
      en: 'Free (125 credits) · Standard: $12/mo · Pro: $28/mo · Unlimited: $76/mo',
      lb: 'Gratis (125 Créditen) · Standard: 12 $/Mount · Pro: 28 $/Mount · Unlimited: 76 $/Mount',
      de: 'Kostenlos (125 Credits) · Standard: 12 $/Monat · Pro: 28 $/Monat · Unlimited: 76 $/Monat',
      it: 'Gratuito (125 crediti) · Standard: 12 $/mese · Pro: 28 $/mese · Unlimited: 76 $/mese',
      pt: 'Gratuito (125 créditos) · Standard: 12 $/mês · Pro: 28 $/mês · Unlimited: 76 $/mês',
    },
    vendor: 'Runway AI',
    founded: '2018',
    headquarters: 'New York, USA',
    euCompliance: {
      gdprCompliant: 'partial',
      euAiActReady: false,
      dataLocation: 'US',
      hasEuDataResidency: false,
      dpaAvailable: true,
      certifications: ['SOC 2 Type II'],
      complianceNote: {
        fr: "\"GDPR Readiness\" déclarée (alignement plutôt que conformité formelle). DPA avec provisions de protection des données pour Enterprise. Assets privés par défaut. ISO 27001 non certifié.",
        en: '"GDPR Readiness" stated (alignment rather than formal compliance). DPA with data protection provisions for Enterprise. Assets private by default. ISO 27001 not certified.',
        lb: '"GDPR Readiness" deklaréiert (Alignement amplaz formell Konformitéit). DPA mat Dateschutzbestëmmunge fir Enterprise.',
        de: '"GDPR Readiness" erklärt (Ausrichtung statt formeller Konformität). AVV mit Datenschutzbestimmungen für Enterprise.',
        it: '"GDPR Readiness" dichiarata (allineamento piuttosto che conformità formale). DPA per Enterprise.',
        pt: '"GDPR Readiness" declarada (alinhamento em vez de conformidade formal). DPA para Enterprise.',
      },
    },
  },
  {
    slug: 'github-copilot',
    name: 'GitHub Copilot',
    description: {
      fr: 'Assistant de programmation IA. Complète votre code, génère des fonctions et aide au débogage.',
      en: 'AI coding assistant. Completes your code, generates functions and helps with debugging.',
      lb: 'KI-Programméierassistent. Komplettéiert Äre Code, generéiert Funktiounen an hëlleft beim Debugging.',
      de: 'KI-Programmierassistent. Vervollständigt Ihren Code, generiert Funktionen und hilft beim Debugging.',
      it: 'Assistente di programmazione IA. Completa il codice, genera funzioni e aiuta nel debugging.',
      pt: 'Assistente de programação IA. Completa o código, gera funções e ajuda na depuração.',
    },
    longDescription: {
      fr: "GitHub Copilot est un assistant de programmation IA développé par Microsoft/GitHub. Il complète votre code, génère des fonctions et aide au débogage directement dans votre IDE. Les données Business/Enterprise ne sont pas utilisées pour l'entraînement.",
      en: 'GitHub Copilot is an AI coding assistant developed by Microsoft/GitHub. It completes your code, generates functions and helps with debugging directly in your IDE. Business/Enterprise data not used for model training.',
      lb: 'GitHub Copilot ass e KI-Programméierassistent entwéckelt vu Microsoft/GitHub. Et komplettéiert Äre Code, generéiert Funktiounen an hëlleft beim Debugging.',
      de: 'GitHub Copilot ist ein KI-Programmierassistent von Microsoft/GitHub. Er vervollständigt Ihren Code, generiert Funktionen und hilft beim Debugging direkt in Ihrer IDE.',
      it: "GitHub Copilot è un assistente di programmazione IA sviluppato da Microsoft/GitHub. Completa il codice, genera funzioni e aiuta nel debugging direttamente nel vostro IDE.",
      pt: 'GitHub Copilot é um assistente de programação IA desenvolvido pela Microsoft/GitHub. Completa o código, gera funções e ajuda na depuração diretamente no seu IDE.',
    },
    category: 'dev',
    url: 'https://github.com/features/copilot',
    tags: ['Code', 'IDE'],
    free: false,
    pricing: {
      fr: 'Individual : 10 $/mois · Business : 19 $/mois · Enterprise : 39 $/mois',
      en: 'Individual: $10/mo · Business: $19/mo · Enterprise: $39/mo',
      lb: 'Individual: 10 $/Mount · Business: 19 $/Mount · Enterprise: 39 $/Mount',
      de: 'Individual: 10 $/Monat · Business: 19 $/Monat · Enterprise: 39 $/Monat',
      it: 'Individual: 10 $/mese · Business: 19 $/mese · Enterprise: 39 $/mese',
      pt: 'Individual: 10 $/mês · Business: 19 $/mês · Enterprise: 39 $/mês',
    },
    vendor: 'Microsoft / GitHub',
    founded: '2021',
    headquarters: 'San Francisco, USA',
    euCompliance: {
      gdprCompliant: true,
      euAiActReady: true,
      dataLocation: 'US (default); EU data residency for repo data',
      hasEuDataResidency: 'partial',
      dpaAvailable: true,
      certifications: ['SOC 2 Type II', 'ISO 27001', 'CSA STAR Level 2'],
      complianceNote: {
        fr: "Conforme RGPD couvert par le programme RGPD de Microsoft. Résidence de données UE pour le code de dépôt (GitHub Enterprise Cloud), mais le traitement IA Copilot peut se faire hors UE. Signataire du Code de pratique de l'UE pour l'IA.",
        en: 'GDPR compliant covered by Microsoft GDPR program. EU data residency for repository code (GitHub Enterprise Cloud), but Copilot AI processing may occur outside EU. Signatory of EU Code of Practice for AI.',
        lb: 'RGPD-konform gedeckt vum Microsoft RGPD-Programm. EU-Datenresidenz fir Repository-Code, awer Copilot KI-Veraarbechtung kann ausserhalb vun der EU sinn.',
        de: 'DSGVO-konform, abgedeckt durch das Microsoft-DSGVO-Programm. EU-Datenresidenz für Repository-Code, aber Copilot-KI-Verarbeitung kann außerhalb der EU stattfinden.',
        it: "Conforme GDPR coperto dal programma GDPR di Microsoft. Residenza dati UE per il codice repository, ma l'elaborazione IA Copilot può avvenire fuori dall'UE.",
        pt: 'Conforme RGPD coberto pelo programa RGPD da Microsoft. Residência de dados UE para código de repositório, mas processamento IA Copilot pode ocorrer fora da UE.',
      },
    },
  },
  {
    slug: 'cursor',
    name: 'Cursor',
    description: {
      fr: "IDE avec IA intégrée. Éditeur de code intelligent qui comprend l'ensemble de votre projet.",
      en: 'AI-native IDE. Smart code editor that understands your entire project.',
      lb: 'KI-nativ IDE. Intelligent Code-Editor deen Äert ganzt Projet versteet.',
      de: 'KI-natives IDE. Intelligenter Code-Editor, der Ihr gesamtes Projekt versteht.',
      it: 'IDE con IA nativa. Editor di codice intelligente che comprende tutto il progetto.',
      pt: 'IDE com IA nativa. Editor de código inteligente que compreende todo o projeto.',
    },
    longDescription: {
      fr: "Cursor est un IDE natif IA qui comprend l'ensemble de votre projet. Mode Privacy disponible (zéro rétention de données avec les fournisseurs LLM). Support de modèles locaux (LLaMA, Mistral) pour une isolation complète des données.",
      en: 'Cursor is an AI-native IDE that understands your entire project. Privacy Mode available (zero data retention with LLM providers). Local model support (LLaMA, Mistral) for full data isolation.',
      lb: 'Cursor ass en KI-nativ IDE dat Äert ganzt Projet versteet. Privacy Mode verfügbar (Null-Datenretentioun mat LLM-Ubidder).',
      de: 'Cursor ist ein KI-natives IDE, das Ihr gesamtes Projekt versteht. Privacy Mode verfügbar (Null-Datenaufbewahrung bei LLM-Anbietern).',
      it: "Cursor è un IDE nativo IA che comprende tutto il progetto. Privacy Mode disponibile (zero retention con i fornitori LLM).",
      pt: 'Cursor é um IDE nativo IA que compreende todo o projeto. Privacy Mode disponível (zero retenção de dados com fornecedores LLM).',
    },
    category: 'dev',
    url: 'https://cursor.com',
    tags: ['IDE', 'AI-native'],
    free: true,
    pricing: {
      fr: 'Hobby : gratuit · Pro : 20 $/mois · Business : 40 $/mois',
      en: 'Hobby: free · Pro: $20/mo · Business: $40/mo',
      lb: 'Hobby: gratis · Pro: 20 $/Mount · Business: 40 $/Mount',
      de: 'Hobby: kostenlos · Pro: 20 $/Monat · Business: 40 $/Monat',
      it: 'Hobby: gratuito · Pro: 20 $/mese · Business: 40 $/mese',
      pt: 'Hobby: gratuito · Pro: 20 $/mês · Business: 40 $/mês',
    },
    vendor: 'Anysphere',
    founded: '2022',
    headquarters: 'San Francisco, USA',
    euCompliance: {
      gdprCompliant: 'partial',
      euAiActReady: false,
      dataLocation: 'US (code sent to US-based LLM providers)',
      hasEuDataResidency: false,
      dpaAvailable: false,
      certifications: ['SOC 2 Type II'],
      complianceNote: {
        fr: "Conformité RGPD déclarée avec chiffrement et contrôles de confidentialité. Pas de DPA publiquement disponible. Privacy Mode disponible (zéro rétention). Prompts conservés 30 jours pour monitoring. Les fragments de code transitent par des LLM US.",
        en: 'Declared GDPR compliance with encryption and privacy controls. No publicly available DPA. Privacy Mode available (zero retention). Prompts stored 30 days for monitoring only. Code fragments transit through US-based LLMs.',
        lb: 'Deklaréiert RGPD-Konformitéit mat Verschlësselung a Privatsphärkontrollen. Keen ëffentlech verfügbaren DPA.',
        de: 'Erklärte DSGVO-Konformität mit Verschlüsselung und Datenschutzkontrollen. Keine öffentlich verfügbare AVV.',
        it: "Conformità GDPR dichiarata con crittografia e controlli privacy. Nessun DPA pubblicamente disponibile.",
        pt: 'Conformidade RGPD declarada com encriptação e controlos de privacidade. Nenhum DPA publicamente disponível.',
      },
    },
  },
  {
    slug: 'v0-by-vercel',
    name: 'v0 by Vercel',
    description: {
      fr: 'Générateur d\'interfaces web par IA. Créez des composants UI à partir de descriptions textuelles.',
      en: 'AI web interface generator. Create UI components from text descriptions.',
      lb: 'KI Web-Interface Generator. Erstellt UI-Komponenten aus Textbeschreiwungen.',
      de: 'KI-Web-Interface-Generator. Erstellen Sie UI-Komponenten aus Textbeschreibungen.',
      it: 'Generatore di interfacce web con IA. Create componenti UI da descrizioni testuali.',
      pt: 'Gerador de interfaces web com IA. Crie componentes UI a partir de descrições textuais.',
    },
    longDescription: {
      fr: "v0 par Vercel est un générateur d'interfaces web par IA. Créez des composants UI React/Next.js à partir de descriptions textuelles. Couvert par le DPA de Vercel et certifié EU-US Data Privacy Framework.",
      en: 'v0 by Vercel is an AI web interface generator. Create React/Next.js UI components from text descriptions. Covered by Vercel DPA and certified under EU-US Data Privacy Framework.',
      lb: 'v0 vu Vercel ass e KI Web-Interface Generator. Erstellt React/Next.js UI-Komponenten aus Textbeschreiwungen. Gedeckt vum Vercel DPA.',
      de: 'v0 von Vercel ist ein KI-Web-Interface-Generator. Erstellen Sie React/Next.js UI-Komponenten aus Textbeschreibungen. Abgedeckt durch Vercel AVV.',
      it: "v0 di Vercel è un generatore di interfacce web con IA. Create componenti UI React/Next.js da descrizioni testuali. Coperto dal DPA di Vercel.",
      pt: 'v0 da Vercel é um gerador de interfaces web com IA. Crie componentes UI React/Next.js a partir de descrições textuais. Coberto pelo DPA da Vercel.',
    },
    category: 'dev',
    url: 'https://v0.dev',
    tags: ['UI', 'React'],
    free: true,
    pricing: {
      fr: 'Gratuit (limité) · Premium : 20 $/mois · Team : 30 $/mois',
      en: 'Free (limited) · Premium: $20/mo · Team: $30/mo',
      lb: 'Gratis (limitéiert) · Premium: 20 $/Mount · Team: 30 $/Mount',
      de: 'Kostenlos (begrenzt) · Premium: 20 $/Monat · Team: 30 $/Monat',
      it: 'Gratuito (limitato) · Premium: 20 $/mese · Team: 30 $/mese',
      pt: 'Gratuito (limitado) · Premium: 20 $/mês · Team: 30 $/mês',
    },
    vendor: 'Vercel',
    founded: '2023',
    headquarters: 'San Francisco, USA',
    euCompliance: {
      gdprCompliant: true,
      euAiActReady: false,
      dataLocation: 'US (default); EU function regions configurable',
      hasEuDataResidency: 'partial',
      dpaAvailable: true,
      certifications: ['SOC 2 Type II', 'ISO 27001:2022', 'PCI DSS'],
      complianceNote: {
        fr: "Couvert par le DPA de Vercel incluant CCT UE. Certifié EU-US Data Privacy Framework. Fonctions UE configurables mais les IP transitent par les US pour la protection DDoS. Sous-traitants IA : Groq, Cerebras, Baseten Labs.",
        en: 'Covered by Vercel DPA including EU SCCs. EU-US Data Privacy Framework certified. EU function regions configurable but IPs transit US for DDoS protection. AI subprocessors: Groq, Cerebras, Baseten Labs.',
        lb: 'Gedeckt vum Vercel DPA inklusive EU-CCT. EU-US Data Privacy Framework zertifizéiert.',
        de: 'Abgedeckt durch Vercel AVV einschließlich EU-SCC. EU-US Data Privacy Framework zertifiziert.',
        it: "Coperto dal DPA di Vercel incluso SCC UE. Certificato EU-US Data Privacy Framework.",
        pt: 'Coberto pelo DPA da Vercel incluindo CCT UE. Certificado EU-US Data Privacy Framework.',
      },
    },
  },
]

export function getAgentBySlug(slug: string): Agent | undefined {
  return AGENTS.find((a) => a.slug === slug)
}

export function getAgentsByCategory(categoryId: string): Agent[] {
  if (categoryId === 'all') return AGENTS
  return AGENTS.filter((a) => a.category === categoryId)
}
